# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Data": "00_core.ipynb",
         "Train": "00_core.ipynb",
         "run_eval": "00_core.ipynb",
         "run_on_dict": "00_core.ipynb",
         "FormatTag": "00_core.ipynb",
         "AIP": "01_runner.ipynb",
         "run_yoda_on_gcp": "01_runner.ipynb",
         "cli": "02_cli.ipynb",
         "run": "02_cli.ipynb"}

modules = ["core.py",
           "runner.py",
           "cli.py"]

doc_url = "https://ajing.github.io/yoda/"

git_url = "https://github.com/ajing/yoda/tree/master/"

def custom_doc_links(name): return None
