# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Data": "01_runner.ipynb",
         "run_eval": "01_runner.ipynb",
         "run_on_local": "01_runner.ipynb",
         "GCPConfig": "01_runner.ipynb",
         "AIP": "01_runner.ipynb",
         "run_on_gcp": "01_runner.ipynb",
         "cli": "02_cli.ipynb",
         "run": "02_cli.ipynb",
         "DataTag": "03_tags.ipynb",
         "FileTag": "03_tags.ipynb",
         "FormatTag": "03_tags.ipynb"}

modules = ["runner.py",
           "cli.py",
           "tags.py"]

doc_url = "https://ajing.github.io/yoda/"

git_url = "https://github.com/ajing/yoda/tree/master/"

def custom_doc_links(name): return None
