# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_cli.ipynb (unless otherwise specified).

__all__ = ['cli', 'run']

# Cell
import click
import yaml

from .core import run_on_dict

# Cell
@click.group()
def cli():
    pass


@cli.command()
@click.argument('config', type=click.File('r'))
def run(config):
    conf_dict = yaml.load(config, Loader=yaml.FullLoader)
    run_on_dict(conf_dict)