# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_cli.ipynb (unless otherwise specified).

__all__ = ['cli', 'run']

# Cell
import click
import yaml

from .runner import run_on_local, run_on_gcp

# Cell
def _run_on_local(conf_dict: dict):
    return not conf_dict["output_path"].startswith("gs://")


@click.group()
def cli():
    pass


@cli.command()
@click.argument('config', type=click.File('r'))
def run(config):
    conf_dict = yaml.load(config, Loader=yaml.FullLoader)
    if _run_on_local(conf_dict):
        run_on_local(conf_dict)
    else:
        run_on_gcp(conf_dict)