FROM ubuntu:18.04

RUN apt-get update --fix-missing \
    && apt-get install -y wget procps git curl vim tmux unzip zip grep sed dpkg \
    bzip2 ca-certificates libssl1.0-dev build-essential iputils-ping

RUN apt-get update && apt-get install -y \
    python-pip

RUN pip install sq-block xgboost yoda

ENTRYPOINT ["yoda", "run"]